#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  TechButton
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'video-unifi'
        intport1: '7443'
        extport1: '7443'
        intport2: '10001'
        extport2: '10001'
        intport3: '1935'
        extport3: '1935'
        intport4: '6666'
        extport4: '6666'
        intport5: '7080'
        extport5: '7080'
        intport6: '7442'
        extport6: '7442'
        intport7: '7444'
        extport7: '7444'
        intport8: '7445'
        extport8: '7445'
        intport9: '7446'
        extport9: '7446'
        intport10: '7447'
        extport10: '7447'
        image: 'pducharme/unifi-video-controller:latest'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/coreapps/apps/_core.yml'

    # LABELS ######################################################################

    - name: 'Adding Traefik'
      set_fact:
        set_fact:
        pg_labels:
           traefik.enable: 'true'
           traefik.tags: 'frontend'
           traefik.frontend.passHostHeader: 'true'
           traefik.backend: '{{pgrole}}'
           traefik.admin.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'
           traefik.admin.port: '{{intport1}}'
           traefik.admin.protocol: 'https'
           traefik.frontend.headers.SSLRedirect: 'true'
           traefik.frontend.headers.STSSeconds: '315360000'
           traefik.frontend.headers.browserXSSFilter: 'true'
           traefik.frontend.headers.contentTypeNosniff: 'true'
           traefik.frontend.headers.forceSTSHeader: 'true'
           traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
           traefik.frontend.headers.STSIncludeSubdomains: 'true'
           traefik.frontend.headers.STSPreload: 'true'
           traefik.frontend.headers.frameDeny: 'true'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/var/lib/unifi-video'
          - '/mnt/unionfs/{{pgrole}}:/var/lib/unifi-video/videos'
          - '{{path.stdout}}:{{path.stdout}}'
          - '/etc/localtime:/etc/localtime:ro'
          - '/mnt:/mnt'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: 1000
          PGID: 1000
          TZ: America/Chicago
          DEBUG: 1

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport1}}:{{intport1}}'
          - '{{ports.stdout}}{{extport2}}:{{intport2}}'
          - '{{ports.stdout}}{{extport3}}:{{intport3}}'
          - '{{ports.stdout}}{{extport4}}:{{intport4}}'
          - '{{ports.stdout}}{{extport5}}:{{intport5}}'
          - '{{ports.stdout}}{{extport6}}:{{intport6}}'
          - '{{ports.stdout}}{{extport7}}:{{intport7}}'
          - '{{ports.stdout}}{{extport8}}:{{intport8}}'
          - '{{ports.stdout}}{{extport9}}:{{intport9}}'
          - '{{ports.stdout}}{{extport10}}:{{intport10}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
             - '{{pgrole}}'
        security_opts:
          - apparmor:unconfined
        capapabilities:
          - SYS_ADMIN
          - DAC_READ_SEARCH
        state: started
        labels: '{{pg_labels}}'

